#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.core.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PS_H2H_BANCO")]
	public partial class PlantillaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertESTADOS_DEMO(ESTADOS_DEMO instance);
    partial void UpdateESTADOS_DEMO(ESTADOS_DEMO instance);
    partial void DeleteESTADOS_DEMO(ESTADOS_DEMO instance);
    #endregion
		
		public PlantillaDataContext() : 
				base(global::Plantilla.core.Properties.Settings.Default.PS_H2H_BANCOConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public PlantillaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PlantillaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PlantillaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PlantillaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ESTADOS_DEMO> ESTADOS_DEMOs
		{
			get
			{
				return this.GetTable<ESTADOS_DEMO>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_EDI_DESCRIPCION_ROL")]
		public int PROC_EDI_DESCRIPCION_ROL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ROL", DbType="Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="VarChar(200)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rOL, dESCRIPCION, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_VAL_USUARIO_SOFTLAND")]
		public ISingleResult<PROC_VAL_USUARIO_SOFTLANDResult> PROC_VAL_USUARIO_SOFTLAND([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(100)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASS", DbType="VarChar(250)")] string pASS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, pASS);
			return ((ISingleResult<PROC_VAL_USUARIO_SOFTLANDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_EDI_ESTADO_USUARIO")]
		public int PROC_EDI_ESTADO_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO", DbType="VarChar(1)")] string eSTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, eSTADO, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_EDI_USUARIO")]
		public int PROC_EDI_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ROL", DbType="Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, rOL, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_INS_ROL")]
		public int PROC_INS_ROL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="VarChar(50)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dESCRIPCION, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_INS_USUARIO")]
		public int PROC_INS_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ROL", DbType="Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, rOL, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_ROLES")]
		public ISingleResult<PROC_OBT_ROLESResult> PROC_OBT_ROLES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_ROLESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_USUARIOS")]
		public ISingleResult<PROC_OBT_USUARIOSResult> PROC_OBT_USUARIOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ROL", DbType="Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rOL, cIA);
			return ((ISingleResult<PROC_OBT_USUARIOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_USUARIOS_PARA_INSERTAR")]
		public ISingleResult<PROC_OBT_USUARIOS_PARA_INSERTARResult> PROC_OBT_USUARIOS_PARA_INSERTAR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_USUARIOS_PARA_INSERTARResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_VAL_USUARIO")]
		public ISingleResult<PROC_VAL_USUARIOResult> PROC_VAL_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(100)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASS", DbType="VarChar(250)")] string pASS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, pASS, cIA);
			return ((ISingleResult<PROC_VAL_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_VAL_USUARIO_ACTIVO")]
		public ISingleResult<PROC_VAL_USUARIO_ACTIVOResult> PROC_VAL_USUARIO_ACTIVO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, cIA);
			return ((ISingleResult<PROC_VAL_USUARIO_ACTIVOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_VAL_USUARIO_ROL")]
		public ISingleResult<PROC_VAL_USUARIO_ROLResult> PROC_VAL_USUARIO_ROL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, cIA);
			return ((ISingleResult<PROC_VAL_USUARIO_ROLResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_CLIENTES_FILTRO")]
		public ISingleResult<PROC_OBT_CLIENTES_FILTROResult> PROC_OBT_CLIENTES_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_CLIENTES_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_DOCUMENTOS_FILTRO")]
		public ISingleResult<PROC_OBT_DOCUMENTOS_FILTROResult> PROC_OBT_DOCUMENTOS_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_DOCUMENTOS_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_PROVEEDORES_FILTRO")]
		public ISingleResult<PROC_OBT_PROVEEDORES_FILTROResult> PROC_OBT_PROVEEDORES_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_PROVEEDORES_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_CUENTAS_BANCARIAS_TODAS_FILTRO")]
		public ISingleResult<PROC_OBT_CUENTAS_BANCARIAS_TODAS_FILTROResult> PROC_OBT_CUENTAS_BANCARIAS_TODAS_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_CUENTAS_BANCARIAS_TODAS_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_TRANSFERENCIAS_FILTRO")]
		public ISingleResult<PROC_OBT_TRANSFERENCIAS_FILTROResult> PROC_OBT_TRANSFERENCIAS_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_TRANSFERENCIAS_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEAR.PROC_ENVIAR_CORREO_PAGO_H2H_MASIVO")]
		public int PROC_ENVIAR_CORREO_PAGO_H2H_MASIVO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEBITO", DbType="VarChar(50)")] string dEBITO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dEBITO, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_ENVIAR_CORREO_PAGO_H2H")]
		public int PROC_ENVIAR_CORREO_PAGO_H2H([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROVEEDOR", DbType="VarChar(50)")] string pROVEEDOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEBITO", DbType="VarChar(50)")] string dEBITO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROVEEDOR, dEBITO, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_INS_DOCUMENTO_CC")]
		public int PROC_INS_DOCUMENTO_CC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUENTA_BANCARIA", DbType="VarChar(22)")] string cUENTA_BANCARIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCUMENTO", DbType="VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(3)")] string tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUBTIPO", DbType="Int")] System.Nullable<int> sUBTIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA", DbType="VarChar(10)")] string fECHA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONCEPTO", DbType="VarChar(240)")] string cONCEPTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTO", DbType="Decimal(28,8)")] System.Nullable<decimal> mONTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONEDA", DbType="VarChar(4)")] string mONEDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_LINEA", DbType="VarChar(20)")] string iD_LINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLIENTE", DbType="VarChar(20)")] string cLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cUENTA_BANCARIA, uSUARIO, dOCUMENTO, tIPO, sUBTIPO, fECHA, cONCEPTO, mONTO, mONEDA, iD_LINEA, cLIENTE, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_SUBTIPOS_CC_FILTRO")]
		public ISingleResult<PROC_OBT_SUBTIPOS_CC_FILTROResult> PROC_OBT_SUBTIPOS_CC_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_SUBTIPOS_CC_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_SUBTIPOS_CC_X_TIPO_FILTRO")]
		public ISingleResult<PROC_OBT_SUBTIPOS_CC_X_TIPO_FILTROResult> PROC_OBT_SUBTIPOS_CC_X_TIPO_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(3)")] string tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO, cIA);
			return ((ISingleResult<PROC_OBT_SUBTIPOS_CC_X_TIPO_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_SUBTIPOS_CP_FILTRO")]
		public ISingleResult<PROC_OBT_SUBTIPOS_CP_FILTROResult> PROC_OBT_SUBTIPOS_CP_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_SUBTIPOS_CP_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_SUBTIPOS_CP_X_TIPO_FILTRO")]
		public ISingleResult<PROC_OBT_SUBTIPOS_CP_X_TIPO_FILTROResult> PROC_OBT_SUBTIPOS_CP_X_TIPO_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(3)")] string tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO, cIA);
			return ((ISingleResult<PROC_OBT_SUBTIPOS_CP_X_TIPO_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_INS_DOCUMENTO_CP")]
		public int PROC_INS_DOCUMENTO_CP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUENTA_BANCARIA", DbType="VarChar(22)")] string cUENTA_BANCARIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCUMENTO", DbType="VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(3)")] string tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUBTIPO", DbType="Int")] System.Nullable<int> sUBTIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA", DbType="VarChar(10)")] string fECHA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONCEPTO", DbType="VarChar(240)")] string cONCEPTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTO", DbType="Decimal(28,8)")] System.Nullable<decimal> mONTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONEDA", DbType="VarChar(4)")] string mONEDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_LINEA", DbType="VarChar(20)")] string iD_LINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROVEEDOR", DbType="VarChar(20)")] string pROVEEDOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cUENTA_BANCARIA, uSUARIO, dOCUMENTO, tIPO, sUBTIPO, fECHA, cONCEPTO, mONTO, mONEDA, iD_LINEA, pROVEEDOR, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_EDI_PERMISOS")]
		public int PROC_EDI_PERMISOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ROL", DbType="Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TRANSFERENCIAS", DbType="Int")] System.Nullable<int> tRANSFERENCIAS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="H2H", DbType="Int")] System.Nullable<int> h2H, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIOS", DbType="Int")] System.Nullable<int> uSUARIOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rOL, tRANSFERENCIAS, h2H, uSUARIOS, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_PERMISOS")]
		public ISingleResult<PROC_OBT_PERMISOSResult> PROC_OBT_PERMISOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_PERMISOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_USUARIO_PERMISOS")]
		public ISingleResult<PROC_OBT_USUARIO_PERMISOSResult> PROC_OBT_USUARIO_PERMISOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ROL", DbType="Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rOL, cIA);
			return ((ISingleResult<PROC_OBT_USUARIO_PERMISOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_TRANSFERENCIAS_LINEAS")]
		public ISingleResult<PROC_OBT_TRANSFERENCIAS_LINEASResult> PROC_OBT_TRANSFERENCIAS_LINEAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TRANSFERENCIA", DbType="VarChar(50)")] string tRANSFERENCIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tRANSFERENCIA, cIA);
			return ((ISingleResult<PROC_OBT_TRANSFERENCIAS_LINEASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_PROVEEDORES_PARA_REPORTE")]
		public ISingleResult<PROC_OBT_PROVEEDORES_PARA_REPORTEResult> PROC_OBT_PROVEEDORES_PARA_REPORTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_ORIGEN", DbType="VarChar(30)")] string nUMERO_ORIGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nUMERO_ORIGEN, cIA);
			return ((ISingleResult<PROC_OBT_PROVEEDORES_PARA_REPORTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_ESTADO_CUENTA_BANCARIO")]
		public ISingleResult<PROC_OBT_ESTADO_CUENTA_BANCARIOResult> PROC_OBT_ESTADO_CUENTA_BANCARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_INICIO", DbType="VarChar(25)")] string fECHA_INICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_FINAL", DbType="VarChar(25)")] string fECHA_FINAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUENTA_BANCARIA", DbType="VarChar(22)")] string cUENTA_BANCARIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(10)")] string tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUBTIPO", DbType="VarChar(10)")] string sUBTIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCUMENTO_SOFTLAND", DbType="VarChar(50)")] string dOCUMENTO_SOFTLAND, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROVEEDOR", DbType="VarChar(20)")] string pROVEEDOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLIENTE", DbType="VarChar(50)")] string cLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEBITO_O_CREDITO", DbType="VarChar(1)")] string dEBITO_O_CREDITO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CXC_CXP", DbType="VarChar(3)")] string cXC_CXP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CARGADO_BANCOS", DbType="VarChar(2)")] string cARGADO_BANCOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fECHA_INICIO, fECHA_FINAL, cUENTA_BANCARIA, tIPO, sUBTIPO, dOCUMENTO_SOFTLAND, pROVEEDOR, cLIENTE, dEBITO_O_CREDITO, cXC_CXP, cARGADO_BANCOS, cIA);
			return ((ISingleResult<PROC_OBT_ESTADO_CUENTA_BANCARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_TRANSFERENCIAS")]
		public ISingleResult<PROC_OBT_TRANSFERENCIASResult> PROC_OBT_TRANSFERENCIAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_INICIO", DbType="VarChar(25)")] string fECHA_INICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_FINAL", DbType="VarChar(25)")] string fECHA_FINAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUENTA_BANCARIA", DbType="VarChar(22)")] string cUENTA_BANCARIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TRANSFERENCIA", DbType="VarChar(50)")] string tRANSFERENCIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROVEEDOR", DbType="VarChar(50)")] string pROVEEDOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fECHA_INICIO, fECHA_FINAL, cUENTA_BANCARIA, tRANSFERENCIA, pROVEEDOR, cIA);
			return ((ISingleResult<PROC_OBT_TRANSFERENCIASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_ESTADO_CUENTA_BANCARIO_PARA_ACCIONES")]
		public ISingleResult<PROC_OBT_ESTADO_CUENTA_BANCARIO_PARA_ACCIONESResult> PROC_OBT_ESTADO_CUENTA_BANCARIO_PARA_ACCIONES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_LINEA", DbType="Int")] System.Nullable<int> iD_LINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_LINEA, cIA);
			return ((ISingleResult<PROC_OBT_ESTADO_CUENTA_BANCARIO_PARA_ACCIONESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_SUBTIPOS_CONTROL_BANCARIO_FILTRO")]
		public ISingleResult<PROC_OBT_SUBTIPOS_CONTROL_BANCARIO_FILTROResult> PROC_OBT_SUBTIPOS_CONTROL_BANCARIO_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_SUBTIPOS_CONTROL_BANCARIO_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_SUBTIPOS_X_TIPO_CONTROL_BANCARIO_FILTRO")]
		public ISingleResult<PROC_OBT_SUBTIPOS_X_TIPO_CONTROL_BANCARIO_FILTROResult> PROC_OBT_SUBTIPOS_X_TIPO_CONTROL_BANCARIO_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(3)")] string tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO, cIA);
			return ((ISingleResult<PROC_OBT_SUBTIPOS_X_TIPO_CONTROL_BANCARIO_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_SUBTIPOS_TODOS_FILTRO")]
		public ISingleResult<PROC_OBT_SUBTIPOS_TODOS_FILTROResult> PROC_OBT_SUBTIPOS_TODOS_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_SUBTIPOS_TODOS_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_INS_DOCUMENTO_MOV_BANCOS")]
		public int PROC_INS_DOCUMENTO_MOV_BANCOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUENTA_BANCARIA", DbType="VarChar(22)")] string cUENTA_BANCARIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCUMENTO", DbType="VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTO", DbType="Decimal(28,8)")] System.Nullable<decimal> mONTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONEDA", DbType="VarChar(4)")] string mONEDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(3)")] string tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUBTIPO", DbType="Int")] System.Nullable<int> sUBTIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA", DbType="VarChar(10)")] string fECHA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONCEPTO", DbType="VarChar(240)")] string cONCEPTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_LINEA", DbType="VarChar(20)")] string iD_LINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cUENTA_BANCARIA, uSUARIO, dOCUMENTO, mONTO, mONEDA, tIPO, sUBTIPO, fECHA, cONCEPTO, iD_LINEA, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_CONCILIACIONES_FILTRO")]
		public ISingleResult<PROC_OBT_CONCILIACIONES_FILTROResult> PROC_OBT_CONCILIACIONES_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUENTA_BANCO", DbType="VarChar(22)")] string cUENTA_BANCO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA", DbType="VarChar(10)")] string fECHA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cUENTA_BANCO, fECHA, cIA);
			return ((ISingleResult<PROC_OBT_CONCILIACIONES_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_CONCILIACIONES_TODAS_FILTRO")]
		public ISingleResult<PROC_OBT_CONCILIACIONES_TODAS_FILTROResult> PROC_OBT_CONCILIACIONES_TODAS_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUENTA_BANCO", DbType="VarChar(22)")] string cUENTA_BANCO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cUENTA_BANCO, cIA);
			return ((ISingleResult<PROC_OBT_CONCILIACIONES_TODAS_FILTROResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_INS_DOCUMENTO_MOV_REPORTADOS")]
		public int PROC_INS_DOCUMENTO_MOV_REPORTADOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUENTA_BANCARIA", DbType="VarChar(22)")] string cUENTA_BANCARIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONCILIACION", DbType="VarChar(20)")] string cONCILIACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCUMENTO", DbType="VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA", DbType="VarChar(10)")] string fECHA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONCEPTO", DbType="VarChar(240)")] string cONCEPTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTO", DbType="Decimal(28,8)")] System.Nullable<decimal> mONTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(3)")] string tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_LINEA", DbType="VarChar(20)")] string iD_LINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cUENTA_BANCARIA, cONCILIACION, uSUARIO, dOCUMENTO, fECHA, cONCEPTO, mONTO, tIPO, iD_LINEA, cIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GLOBAL.PROC_OBT_CUENTAS_BANCARIAS_FILTRO")]
		public ISingleResult<PROC_OBT_CUENTAS_BANCARIAS_FILTROResult> PROC_OBT_CUENTAS_BANCARIAS_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CIA", DbType="VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_CUENTAS_BANCARIAS_FILTROResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ATCL.ESTADOS_DEMO")]
	public partial class ESTADOS_DEMO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _DESCRIP;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnDESCRIPChanging(string value);
    partial void OnDESCRIPChanged();
    #endregion
		
		public ESTADOS_DEMO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(1) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIP", DbType="VarChar(100)")]
		public string DESCRIP
		{
			get
			{
				return this._DESCRIP;
			}
			set
			{
				if ((this._DESCRIP != value))
				{
					this.OnDESCRIPChanging(value);
					this.SendPropertyChanging();
					this._DESCRIP = value;
					this.SendPropertyChanged("DESCRIP");
					this.OnDESCRIPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class PROC_VAL_USUARIO_SOFTLANDResult
	{
		
		private System.Nullable<int> _VALID;
		
		public PROC_VAL_USUARIO_SOFTLANDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALID", DbType="Int")]
		public System.Nullable<int> VALID
		{
			get
			{
				return this._VALID;
			}
			set
			{
				if ((this._VALID != value))
				{
					this._VALID = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_ROLESResult
	{
		
		private System.Nullable<int> _ROL;
		
		private string _DESCRIPCION;
		
		public PROC_OBT_ROLESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL", DbType="Int")]
		public System.Nullable<int> ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(200)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_USUARIOSResult
	{
		
		private string _USUARIO;
		
		private string _NOMBRE;
		
		private System.Nullable<int> _ROL;
		
		private string _ROL_DESCRIPCION;
		
		private string _ESTADO;
		
		public PROC_OBT_USUARIOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO", DbType="VarChar(50)")]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this._USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(150)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL", DbType="Int")]
		public System.Nullable<int> ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL_DESCRIPCION", DbType="VarChar(50)")]
		public string ROL_DESCRIPCION
		{
			get
			{
				return this._ROL_DESCRIPCION;
			}
			set
			{
				if ((this._ROL_DESCRIPCION != value))
				{
					this._ROL_DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(1)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_USUARIOS_PARA_INSERTARResult
	{
		
		private string _USUARIO;
		
		private string _DESCRIPCION;
		
		public PROC_OBT_USUARIOS_PARA_INSERTARResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO", DbType="VarChar(50)")]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this._USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(100)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class PROC_VAL_USUARIOResult
	{
		
		private System.Nullable<int> _VALID;
		
		public PROC_VAL_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALID", DbType="Int")]
		public System.Nullable<int> VALID
		{
			get
			{
				return this._VALID;
			}
			set
			{
				if ((this._VALID != value))
				{
					this._VALID = value;
				}
			}
		}
	}
	
	public partial class PROC_VAL_USUARIO_ACTIVOResult
	{
		
		private string _ACTIVO;
		
		public PROC_VAL_USUARIO_ACTIVOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="VarChar(1)")]
		public string ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
	}
	
	public partial class PROC_VAL_USUARIO_ROLResult
	{
		
		private System.Nullable<int> _ROL;
		
		private string _DESCRIPCION;
		
		private string _USUARIO;
		
		private string _CIA;
		
		private string _NOMBRE;
		
		private string _CORREO;
		
		public PROC_VAL_USUARIO_ROLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL", DbType="Int")]
		public System.Nullable<int> ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO", DbType="VarChar(50)")]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this._USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIA", DbType="VarChar(30)")]
		public string CIA
		{
			get
			{
				return this._CIA;
			}
			set
			{
				if ((this._CIA != value))
				{
					this._CIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(150)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(255)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_CLIENTES_FILTROResult
	{
		
		private string _CLIENTE;
		
		private string _COMPLETO;
		
		public PROC_OBT_CLIENTES_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENTE", DbType="VarChar(50)")]
		public string CLIENTE
		{
			get
			{
				return this._CLIENTE;
			}
			set
			{
				if ((this._CLIENTE != value))
				{
					this._CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLETO", DbType="VarChar(200)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_DOCUMENTOS_FILTROResult
	{
		
		private string _DOCUMENTO;
		
		public PROC_OBT_DOCUMENTOS_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENTO", DbType="VarChar(50)")]
		public string DOCUMENTO
		{
			get
			{
				return this._DOCUMENTO;
			}
			set
			{
				if ((this._DOCUMENTO != value))
				{
					this._DOCUMENTO = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_PROVEEDORES_FILTROResult
	{
		
		private string _PROVEEDOR;
		
		private string _COMPLETO;
		
		public PROC_OBT_PROVEEDORES_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVEEDOR", DbType="VarChar(50)")]
		public string PROVEEDOR
		{
			get
			{
				return this._PROVEEDOR;
			}
			set
			{
				if ((this._PROVEEDOR != value))
				{
					this._PROVEEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLETO", DbType="VarChar(200)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_CUENTAS_BANCARIAS_TODAS_FILTROResult
	{
		
		private string _CUENTA_BANCO;
		
		private string _COMPLETO;
		
		public PROC_OBT_CUENTAS_BANCARIAS_TODAS_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUENTA_BANCO", DbType="VarChar(22)")]
		public string CUENTA_BANCO
		{
			get
			{
				return this._CUENTA_BANCO;
			}
			set
			{
				if ((this._CUENTA_BANCO != value))
				{
					this._CUENTA_BANCO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLETO", DbType="VarChar(100)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_TRANSFERENCIAS_FILTROResult
	{
		
		private System.Nullable<int> _TRANSFERENCIA;
		
		public PROC_OBT_TRANSFERENCIAS_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSFERENCIA", DbType="Int")]
		public System.Nullable<int> TRANSFERENCIA
		{
			get
			{
				return this._TRANSFERENCIA;
			}
			set
			{
				if ((this._TRANSFERENCIA != value))
				{
					this._TRANSFERENCIA = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_SUBTIPOS_CC_FILTROResult
	{
		
		private System.Nullable<int> _SUBTIPO;
		
		private string _DESCRIPCION;
		
		public PROC_OBT_SUBTIPOS_CC_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTIPO", DbType="Int")]
		public System.Nullable<int> SUBTIPO
		{
			get
			{
				return this._SUBTIPO;
			}
			set
			{
				if ((this._SUBTIPO != value))
				{
					this._SUBTIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(30)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_SUBTIPOS_CC_X_TIPO_FILTROResult
	{
		
		private System.Nullable<int> _SUBTIPO;
		
		private string _DESCRIPCION;
		
		public PROC_OBT_SUBTIPOS_CC_X_TIPO_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTIPO", DbType="Int")]
		public System.Nullable<int> SUBTIPO
		{
			get
			{
				return this._SUBTIPO;
			}
			set
			{
				if ((this._SUBTIPO != value))
				{
					this._SUBTIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(30)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_SUBTIPOS_CP_FILTROResult
	{
		
		private System.Nullable<int> _SUBTIPO;
		
		private string _DESCRIPCION;
		
		public PROC_OBT_SUBTIPOS_CP_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTIPO", DbType="Int")]
		public System.Nullable<int> SUBTIPO
		{
			get
			{
				return this._SUBTIPO;
			}
			set
			{
				if ((this._SUBTIPO != value))
				{
					this._SUBTIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(30)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_SUBTIPOS_CP_X_TIPO_FILTROResult
	{
		
		private System.Nullable<int> _SUBTIPO;
		
		private string _DESCRIPCION;
		
		public PROC_OBT_SUBTIPOS_CP_X_TIPO_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTIPO", DbType="Int")]
		public System.Nullable<int> SUBTIPO
		{
			get
			{
				return this._SUBTIPO;
			}
			set
			{
				if ((this._SUBTIPO != value))
				{
					this._SUBTIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(30)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_PERMISOSResult
	{
		
		private System.Nullable<int> _ROL;
		
		private string _DESCRIPCION;
		
		private string _TRANSFERENCIAS;
		
		private string _H2H;
		
		private string _USUARIOS;
		
		public PROC_OBT_PERMISOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL", DbType="Int")]
		public System.Nullable<int> ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSFERENCIAS", DbType="VarChar(1)")]
		public string TRANSFERENCIAS
		{
			get
			{
				return this._TRANSFERENCIAS;
			}
			set
			{
				if ((this._TRANSFERENCIAS != value))
				{
					this._TRANSFERENCIAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H2H", DbType="VarChar(1)")]
		public string H2H
		{
			get
			{
				return this._H2H;
			}
			set
			{
				if ((this._H2H != value))
				{
					this._H2H = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOS", DbType="VarChar(1)")]
		public string USUARIOS
		{
			get
			{
				return this._USUARIOS;
			}
			set
			{
				if ((this._USUARIOS != value))
				{
					this._USUARIOS = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_USUARIO_PERMISOSResult
	{
		
		private System.Nullable<int> _ROL;
		
		private string _DESCRIPCION;
		
		private System.Nullable<int> _TRANSFERENCIAS;
		
		private System.Nullable<int> _H2H;
		
		private System.Nullable<int> _USUARIOS;
		
		public PROC_OBT_USUARIO_PERMISOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL", DbType="Int")]
		public System.Nullable<int> ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSFERENCIAS", DbType="Int")]
		public System.Nullable<int> TRANSFERENCIAS
		{
			get
			{
				return this._TRANSFERENCIAS;
			}
			set
			{
				if ((this._TRANSFERENCIAS != value))
				{
					this._TRANSFERENCIAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H2H", DbType="Int")]
		public System.Nullable<int> H2H
		{
			get
			{
				return this._H2H;
			}
			set
			{
				if ((this._H2H != value))
				{
					this._H2H = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOS", DbType="Int")]
		public System.Nullable<int> USUARIOS
		{
			get
			{
				return this._USUARIOS;
			}
			set
			{
				if ((this._USUARIOS != value))
				{
					this._USUARIOS = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_TRANSFERENCIAS_LINEASResult
	{
		
		private string _PROVEEDOR_COMPLETO;
		
		private string _PROVEEDOR;
		
		private string _CONCEPTO;
		
		private string _CUENTA_DESTINO;
		
		private string _SALDO;
		
		private string _MONEDA_PAGO;
		
		private string _MONEDA_PROVEEDOR;
		
		private string _MONTO_A_PAGAR;
		
		private System.Nullable<int> _NUMERO_ORIGEN;
		
		private string _PROVEEDOR_CRYSTAL;
		
		private string _CORREO_PROVEEDOR;
		
		private string _FECHA_DOC_STR;
		
		private string _MONTO_DOC_STR;
		
		private string _ORDEN_COMPRA;
		
		private string _TIPO;
		
		private string _SALDO_DOC_STR;
		
		public PROC_OBT_TRANSFERENCIAS_LINEASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVEEDOR_COMPLETO", DbType="VarChar(200)")]
		public string PROVEEDOR_COMPLETO
		{
			get
			{
				return this._PROVEEDOR_COMPLETO;
			}
			set
			{
				if ((this._PROVEEDOR_COMPLETO != value))
				{
					this._PROVEEDOR_COMPLETO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVEEDOR", DbType="VarChar(50)")]
		public string PROVEEDOR
		{
			get
			{
				return this._PROVEEDOR;
			}
			set
			{
				if ((this._PROVEEDOR != value))
				{
					this._PROVEEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONCEPTO", DbType="VarChar(50)")]
		public string CONCEPTO
		{
			get
			{
				return this._CONCEPTO;
			}
			set
			{
				if ((this._CONCEPTO != value))
				{
					this._CONCEPTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUENTA_DESTINO", DbType="VarChar(22)")]
		public string CUENTA_DESTINO
		{
			get
			{
				return this._CUENTA_DESTINO;
			}
			set
			{
				if ((this._CUENTA_DESTINO != value))
				{
					this._CUENTA_DESTINO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO", DbType="VarChar(50)")]
		public string SALDO
		{
			get
			{
				return this._SALDO;
			}
			set
			{
				if ((this._SALDO != value))
				{
					this._SALDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONEDA_PAGO", DbType="VarChar(4)")]
		public string MONEDA_PAGO
		{
			get
			{
				return this._MONEDA_PAGO;
			}
			set
			{
				if ((this._MONEDA_PAGO != value))
				{
					this._MONEDA_PAGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONEDA_PROVEEDOR", DbType="VarChar(4)")]
		public string MONEDA_PROVEEDOR
		{
			get
			{
				return this._MONEDA_PROVEEDOR;
			}
			set
			{
				if ((this._MONEDA_PROVEEDOR != value))
				{
					this._MONEDA_PROVEEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO_A_PAGAR", DbType="VarChar(50)")]
		public string MONTO_A_PAGAR
		{
			get
			{
				return this._MONTO_A_PAGAR;
			}
			set
			{
				if ((this._MONTO_A_PAGAR != value))
				{
					this._MONTO_A_PAGAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_ORIGEN", DbType="Int")]
		public System.Nullable<int> NUMERO_ORIGEN
		{
			get
			{
				return this._NUMERO_ORIGEN;
			}
			set
			{
				if ((this._NUMERO_ORIGEN != value))
				{
					this._NUMERO_ORIGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVEEDOR_CRYSTAL", DbType="VarChar(50)")]
		public string PROVEEDOR_CRYSTAL
		{
			get
			{
				return this._PROVEEDOR_CRYSTAL;
			}
			set
			{
				if ((this._PROVEEDOR_CRYSTAL != value))
				{
					this._PROVEEDOR_CRYSTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_PROVEEDOR", DbType="VarChar(200)")]
		public string CORREO_PROVEEDOR
		{
			get
			{
				return this._CORREO_PROVEEDOR;
			}
			set
			{
				if ((this._CORREO_PROVEEDOR != value))
				{
					this._CORREO_PROVEEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_DOC_STR", DbType="VarChar(10)")]
		public string FECHA_DOC_STR
		{
			get
			{
				return this._FECHA_DOC_STR;
			}
			set
			{
				if ((this._FECHA_DOC_STR != value))
				{
					this._FECHA_DOC_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO_DOC_STR", DbType="VarChar(50)")]
		public string MONTO_DOC_STR
		{
			get
			{
				return this._MONTO_DOC_STR;
			}
			set
			{
				if ((this._MONTO_DOC_STR != value))
				{
					this._MONTO_DOC_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDEN_COMPRA", DbType="VarChar(20)")]
		public string ORDEN_COMPRA
		{
			get
			{
				return this._ORDEN_COMPRA;
			}
			set
			{
				if ((this._ORDEN_COMPRA != value))
				{
					this._ORDEN_COMPRA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="VarChar(4)")]
		public string TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this._TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO_DOC_STR", DbType="VarChar(50)")]
		public string SALDO_DOC_STR
		{
			get
			{
				return this._SALDO_DOC_STR;
			}
			set
			{
				if ((this._SALDO_DOC_STR != value))
				{
					this._SALDO_DOC_STR = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_PROVEEDORES_PARA_REPORTEResult
	{
		
		private string _PROVEEDOR_CRYSTAL;
		
		private string _NUMERO;
		
		public PROC_OBT_PROVEEDORES_PARA_REPORTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVEEDOR_CRYSTAL", DbType="VarChar(30)")]
		public string PROVEEDOR_CRYSTAL
		{
			get
			{
				return this._PROVEEDOR_CRYSTAL;
			}
			set
			{
				if ((this._PROVEEDOR_CRYSTAL != value))
				{
					this._PROVEEDOR_CRYSTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO", DbType="VarChar(30)")]
		public string NUMERO
		{
			get
			{
				return this._NUMERO;
			}
			set
			{
				if ((this._NUMERO != value))
				{
					this._NUMERO = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_ESTADO_CUENTA_BANCARIOResult
	{
		
		private System.Nullable<int> _ID_H2H;
		
		private System.Nullable<int> _ID_LINEA;
		
		private string _CUENTA_BANCO;
		
		private string _REFERENCIA;
		
		private string _TIPO;
		
		private string _SUBTIPO;
		
		private string _DOCUMENTO;
		
		private string _CARGADO_ERP;
		
		private System.Nullable<System.DateTime> _FECHA_TEF;
		
		private string _FECHA_TEF_STR;
		
		private string _PS_86_REFERENCIA;
		
		private System.Nullable<decimal> _CREDITO;
		
		private System.Nullable<decimal> _DEBITO;
		
		private string _CREDITO_STR;
		
		private string _DEBITO_STR;
		
		private string _CREDITO_DEBITO;
		
		private string _ESTADO_CB;
		
		private System.Nullable<System.DateTime> _FECHA_MT;
		
		private string _FECHA_MT_STR;
		
		private string _PROVEEDOR;
		
		private string _CLIENTE;
		
		private string _CC_CP;
		
		private string _MONEDA;
		
		private string _ASOCIADO_H2H;
		
		public PROC_OBT_ESTADO_CUENTA_BANCARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_H2H", DbType="Int")]
		public System.Nullable<int> ID_H2H
		{
			get
			{
				return this._ID_H2H;
			}
			set
			{
				if ((this._ID_H2H != value))
				{
					this._ID_H2H = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LINEA", DbType="Int")]
		public System.Nullable<int> ID_LINEA
		{
			get
			{
				return this._ID_LINEA;
			}
			set
			{
				if ((this._ID_LINEA != value))
				{
					this._ID_LINEA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUENTA_BANCO", DbType="VarChar(22)")]
		public string CUENTA_BANCO
		{
			get
			{
				return this._CUENTA_BANCO;
			}
			set
			{
				if ((this._CUENTA_BANCO != value))
				{
					this._CUENTA_BANCO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERENCIA", DbType="VarChar(50)")]
		public string REFERENCIA
		{
			get
			{
				return this._REFERENCIA;
			}
			set
			{
				if ((this._REFERENCIA != value))
				{
					this._REFERENCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="VarChar(10)")]
		public string TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this._TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTIPO", DbType="VarChar(10)")]
		public string SUBTIPO
		{
			get
			{
				return this._SUBTIPO;
			}
			set
			{
				if ((this._SUBTIPO != value))
				{
					this._SUBTIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENTO", DbType="VarChar(50)")]
		public string DOCUMENTO
		{
			get
			{
				return this._DOCUMENTO;
			}
			set
			{
				if ((this._DOCUMENTO != value))
				{
					this._DOCUMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARGADO_ERP", DbType="VarChar(2)")]
		public string CARGADO_ERP
		{
			get
			{
				return this._CARGADO_ERP;
			}
			set
			{
				if ((this._CARGADO_ERP != value))
				{
					this._CARGADO_ERP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TEF", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_TEF
		{
			get
			{
				return this._FECHA_TEF;
			}
			set
			{
				if ((this._FECHA_TEF != value))
				{
					this._FECHA_TEF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TEF_STR", DbType="VarChar(10)")]
		public string FECHA_TEF_STR
		{
			get
			{
				return this._FECHA_TEF_STR;
			}
			set
			{
				if ((this._FECHA_TEF_STR != value))
				{
					this._FECHA_TEF_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PS_86_REFERENCIA", DbType="VarChar(200)")]
		public string PS_86_REFERENCIA
		{
			get
			{
				return this._PS_86_REFERENCIA;
			}
			set
			{
				if ((this._PS_86_REFERENCIA != value))
				{
					this._PS_86_REFERENCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDITO", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> CREDITO
		{
			get
			{
				return this._CREDITO;
			}
			set
			{
				if ((this._CREDITO != value))
				{
					this._CREDITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEBITO", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> DEBITO
		{
			get
			{
				return this._DEBITO;
			}
			set
			{
				if ((this._DEBITO != value))
				{
					this._DEBITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDITO_STR", DbType="VarChar(50)")]
		public string CREDITO_STR
		{
			get
			{
				return this._CREDITO_STR;
			}
			set
			{
				if ((this._CREDITO_STR != value))
				{
					this._CREDITO_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEBITO_STR", DbType="VarChar(50)")]
		public string DEBITO_STR
		{
			get
			{
				return this._DEBITO_STR;
			}
			set
			{
				if ((this._DEBITO_STR != value))
				{
					this._DEBITO_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDITO_DEBITO", DbType="VarChar(1)")]
		public string CREDITO_DEBITO
		{
			get
			{
				return this._CREDITO_DEBITO;
			}
			set
			{
				if ((this._CREDITO_DEBITO != value))
				{
					this._CREDITO_DEBITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_CB", DbType="VarChar(20)")]
		public string ESTADO_CB
		{
			get
			{
				return this._ESTADO_CB;
			}
			set
			{
				if ((this._ESTADO_CB != value))
				{
					this._ESTADO_CB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_MT", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_MT
		{
			get
			{
				return this._FECHA_MT;
			}
			set
			{
				if ((this._FECHA_MT != value))
				{
					this._FECHA_MT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_MT_STR", DbType="VarChar(10)")]
		public string FECHA_MT_STR
		{
			get
			{
				return this._FECHA_MT_STR;
			}
			set
			{
				if ((this._FECHA_MT_STR != value))
				{
					this._FECHA_MT_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVEEDOR", DbType="VarChar(50)")]
		public string PROVEEDOR
		{
			get
			{
				return this._PROVEEDOR;
			}
			set
			{
				if ((this._PROVEEDOR != value))
				{
					this._PROVEEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENTE", DbType="VarChar(50)")]
		public string CLIENTE
		{
			get
			{
				return this._CLIENTE;
			}
			set
			{
				if ((this._CLIENTE != value))
				{
					this._CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_CP", DbType="VarChar(3)")]
		public string CC_CP
		{
			get
			{
				return this._CC_CP;
			}
			set
			{
				if ((this._CC_CP != value))
				{
					this._CC_CP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONEDA", DbType="VarChar(4)")]
		public string MONEDA
		{
			get
			{
				return this._MONEDA;
			}
			set
			{
				if ((this._MONEDA != value))
				{
					this._MONEDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASOCIADO_H2H", DbType="VarChar(1)")]
		public string ASOCIADO_H2H
		{
			get
			{
				return this._ASOCIADO_H2H;
			}
			set
			{
				if ((this._ASOCIADO_H2H != value))
				{
					this._ASOCIADO_H2H = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_TRANSFERENCIASResult
	{
		
		private System.Nullable<int> _TRANSFERENCIA;
		
		private System.Nullable<System.DateTime> _FECHA;
		
		private string _FECHA_STR;
		
		private string _DETALLE;
		
		private string _ENTIDAD_FINANCIERA;
		
		private string _CUENTA_BANCO;
		
		private string _CUENTA_BANCO_DESC;
		
		private string _MONEDA;
		
		private System.Nullable<decimal> _MONTO;
		
		private string _MONTO_STR;
		
		private string _PROVEEDOR;
		
		private string _PROVEEDOR_COMPLETO;
		
		private string _H2H_ENVIADO;
		
		private string _PROVEEDOR_CRYSTAL;
		
		private string _CORREO_PROVEEDOR;
		
		private string _U_PS_H2H_NUM_BANCO;
		
		private string _U_PS_H2H_EMAIL_ENVIADO;
		
		public PROC_OBT_TRANSFERENCIASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSFERENCIA", DbType="Int")]
		public System.Nullable<int> TRANSFERENCIA
		{
			get
			{
				return this._TRANSFERENCIA;
			}
			set
			{
				if ((this._TRANSFERENCIA != value))
				{
					this._TRANSFERENCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this._FECHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_STR", DbType="VarChar(10)")]
		public string FECHA_STR
		{
			get
			{
				return this._FECHA_STR;
			}
			set
			{
				if ((this._FECHA_STR != value))
				{
					this._FECHA_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETALLE", DbType="VarChar(200)")]
		public string DETALLE
		{
			get
			{
				return this._DETALLE;
			}
			set
			{
				if ((this._DETALLE != value))
				{
					this._DETALLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTIDAD_FINANCIERA", DbType="VarChar(50)")]
		public string ENTIDAD_FINANCIERA
		{
			get
			{
				return this._ENTIDAD_FINANCIERA;
			}
			set
			{
				if ((this._ENTIDAD_FINANCIERA != value))
				{
					this._ENTIDAD_FINANCIERA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUENTA_BANCO", DbType="VarChar(22)")]
		public string CUENTA_BANCO
		{
			get
			{
				return this._CUENTA_BANCO;
			}
			set
			{
				if ((this._CUENTA_BANCO != value))
				{
					this._CUENTA_BANCO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUENTA_BANCO_DESC", DbType="VarChar(200)")]
		public string CUENTA_BANCO_DESC
		{
			get
			{
				return this._CUENTA_BANCO_DESC;
			}
			set
			{
				if ((this._CUENTA_BANCO_DESC != value))
				{
					this._CUENTA_BANCO_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONEDA", DbType="VarChar(4)")]
		public string MONEDA
		{
			get
			{
				return this._MONEDA;
			}
			set
			{
				if ((this._MONEDA != value))
				{
					this._MONEDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> MONTO
		{
			get
			{
				return this._MONTO;
			}
			set
			{
				if ((this._MONTO != value))
				{
					this._MONTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO_STR", DbType="VarChar(50)")]
		public string MONTO_STR
		{
			get
			{
				return this._MONTO_STR;
			}
			set
			{
				if ((this._MONTO_STR != value))
				{
					this._MONTO_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVEEDOR", DbType="VarChar(20)")]
		public string PROVEEDOR
		{
			get
			{
				return this._PROVEEDOR;
			}
			set
			{
				if ((this._PROVEEDOR != value))
				{
					this._PROVEEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVEEDOR_COMPLETO", DbType="VarChar(200)")]
		public string PROVEEDOR_COMPLETO
		{
			get
			{
				return this._PROVEEDOR_COMPLETO;
			}
			set
			{
				if ((this._PROVEEDOR_COMPLETO != value))
				{
					this._PROVEEDOR_COMPLETO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H2H_ENVIADO", DbType="VarChar(1)")]
		public string H2H_ENVIADO
		{
			get
			{
				return this._H2H_ENVIADO;
			}
			set
			{
				if ((this._H2H_ENVIADO != value))
				{
					this._H2H_ENVIADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVEEDOR_CRYSTAL", DbType="VarChar(50)")]
		public string PROVEEDOR_CRYSTAL
		{
			get
			{
				return this._PROVEEDOR_CRYSTAL;
			}
			set
			{
				if ((this._PROVEEDOR_CRYSTAL != value))
				{
					this._PROVEEDOR_CRYSTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_PROVEEDOR", DbType="VarChar(200)")]
		public string CORREO_PROVEEDOR
		{
			get
			{
				return this._CORREO_PROVEEDOR;
			}
			set
			{
				if ((this._CORREO_PROVEEDOR != value))
				{
					this._CORREO_PROVEEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_PS_H2H_NUM_BANCO", DbType="VarChar(20)")]
		public string U_PS_H2H_NUM_BANCO
		{
			get
			{
				return this._U_PS_H2H_NUM_BANCO;
			}
			set
			{
				if ((this._U_PS_H2H_NUM_BANCO != value))
				{
					this._U_PS_H2H_NUM_BANCO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_PS_H2H_EMAIL_ENVIADO", DbType="VarChar(1)")]
		public string U_PS_H2H_EMAIL_ENVIADO
		{
			get
			{
				return this._U_PS_H2H_EMAIL_ENVIADO;
			}
			set
			{
				if ((this._U_PS_H2H_EMAIL_ENVIADO != value))
				{
					this._U_PS_H2H_EMAIL_ENVIADO = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_ESTADO_CUENTA_BANCARIO_PARA_ACCIONESResult
	{
		
		private System.Nullable<int> _ID_H2H;
		
		private string _ID_LINEA;
		
		private string _CUENTA_BANCO;
		
		private string _REFERENCIA;
		
		private string _TIPO;
		
		private string _SUBTIPO;
		
		private string _DOCUMENTO;
		
		private string _CARGADO_ERP;
		
		private System.Nullable<System.DateTime> _FECHA_TEF;
		
		private string _FECHA_TEF_STR;
		
		private string _PS_86_REFERENCIA;
		
		private System.Nullable<decimal> _CREDITO;
		
		private System.Nullable<decimal> _DEBITO;
		
		private string _CREDITO_STR;
		
		private string _DEBITO_STR;
		
		private string _CREDITO_DEBITO;
		
		private string _ESTADO_CB;
		
		private System.Nullable<System.DateTime> _FECHA_MT;
		
		private string _FECHA_MT_STR;
		
		private string _PROVEEDOR;
		
		private string _CLIENTE;
		
		private string _CC_CP;
		
		private string _MONEDA;
		
		private string _ASOCIADO_H2H;
		
		private string _MONTO;
		
		public PROC_OBT_ESTADO_CUENTA_BANCARIO_PARA_ACCIONESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_H2H", DbType="Int")]
		public System.Nullable<int> ID_H2H
		{
			get
			{
				return this._ID_H2H;
			}
			set
			{
				if ((this._ID_H2H != value))
				{
					this._ID_H2H = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LINEA", DbType="VarChar(20)")]
		public string ID_LINEA
		{
			get
			{
				return this._ID_LINEA;
			}
			set
			{
				if ((this._ID_LINEA != value))
				{
					this._ID_LINEA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUENTA_BANCO", DbType="VarChar(22)")]
		public string CUENTA_BANCO
		{
			get
			{
				return this._CUENTA_BANCO;
			}
			set
			{
				if ((this._CUENTA_BANCO != value))
				{
					this._CUENTA_BANCO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERENCIA", DbType="VarChar(50)")]
		public string REFERENCIA
		{
			get
			{
				return this._REFERENCIA;
			}
			set
			{
				if ((this._REFERENCIA != value))
				{
					this._REFERENCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="VarChar(10)")]
		public string TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this._TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTIPO", DbType="VarChar(10)")]
		public string SUBTIPO
		{
			get
			{
				return this._SUBTIPO;
			}
			set
			{
				if ((this._SUBTIPO != value))
				{
					this._SUBTIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENTO", DbType="VarChar(50)")]
		public string DOCUMENTO
		{
			get
			{
				return this._DOCUMENTO;
			}
			set
			{
				if ((this._DOCUMENTO != value))
				{
					this._DOCUMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARGADO_ERP", DbType="VarChar(2)")]
		public string CARGADO_ERP
		{
			get
			{
				return this._CARGADO_ERP;
			}
			set
			{
				if ((this._CARGADO_ERP != value))
				{
					this._CARGADO_ERP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TEF", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_TEF
		{
			get
			{
				return this._FECHA_TEF;
			}
			set
			{
				if ((this._FECHA_TEF != value))
				{
					this._FECHA_TEF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TEF_STR", DbType="VarChar(10)")]
		public string FECHA_TEF_STR
		{
			get
			{
				return this._FECHA_TEF_STR;
			}
			set
			{
				if ((this._FECHA_TEF_STR != value))
				{
					this._FECHA_TEF_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PS_86_REFERENCIA", DbType="VarChar(200)")]
		public string PS_86_REFERENCIA
		{
			get
			{
				return this._PS_86_REFERENCIA;
			}
			set
			{
				if ((this._PS_86_REFERENCIA != value))
				{
					this._PS_86_REFERENCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDITO", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> CREDITO
		{
			get
			{
				return this._CREDITO;
			}
			set
			{
				if ((this._CREDITO != value))
				{
					this._CREDITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEBITO", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> DEBITO
		{
			get
			{
				return this._DEBITO;
			}
			set
			{
				if ((this._DEBITO != value))
				{
					this._DEBITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDITO_STR", DbType="VarChar(50)")]
		public string CREDITO_STR
		{
			get
			{
				return this._CREDITO_STR;
			}
			set
			{
				if ((this._CREDITO_STR != value))
				{
					this._CREDITO_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEBITO_STR", DbType="VarChar(50)")]
		public string DEBITO_STR
		{
			get
			{
				return this._DEBITO_STR;
			}
			set
			{
				if ((this._DEBITO_STR != value))
				{
					this._DEBITO_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDITO_DEBITO", DbType="VarChar(1)")]
		public string CREDITO_DEBITO
		{
			get
			{
				return this._CREDITO_DEBITO;
			}
			set
			{
				if ((this._CREDITO_DEBITO != value))
				{
					this._CREDITO_DEBITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_CB", DbType="VarChar(20)")]
		public string ESTADO_CB
		{
			get
			{
				return this._ESTADO_CB;
			}
			set
			{
				if ((this._ESTADO_CB != value))
				{
					this._ESTADO_CB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_MT", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_MT
		{
			get
			{
				return this._FECHA_MT;
			}
			set
			{
				if ((this._FECHA_MT != value))
				{
					this._FECHA_MT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_MT_STR", DbType="VarChar(10)")]
		public string FECHA_MT_STR
		{
			get
			{
				return this._FECHA_MT_STR;
			}
			set
			{
				if ((this._FECHA_MT_STR != value))
				{
					this._FECHA_MT_STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVEEDOR", DbType="VarChar(50)")]
		public string PROVEEDOR
		{
			get
			{
				return this._PROVEEDOR;
			}
			set
			{
				if ((this._PROVEEDOR != value))
				{
					this._PROVEEDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENTE", DbType="VarChar(50)")]
		public string CLIENTE
		{
			get
			{
				return this._CLIENTE;
			}
			set
			{
				if ((this._CLIENTE != value))
				{
					this._CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_CP", DbType="VarChar(3)")]
		public string CC_CP
		{
			get
			{
				return this._CC_CP;
			}
			set
			{
				if ((this._CC_CP != value))
				{
					this._CC_CP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONEDA", DbType="VarChar(4)")]
		public string MONEDA
		{
			get
			{
				return this._MONEDA;
			}
			set
			{
				if ((this._MONEDA != value))
				{
					this._MONEDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASOCIADO_H2H", DbType="VarChar(1)")]
		public string ASOCIADO_H2H
		{
			get
			{
				return this._ASOCIADO_H2H;
			}
			set
			{
				if ((this._ASOCIADO_H2H != value))
				{
					this._ASOCIADO_H2H = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO", DbType="VarChar(50)")]
		public string MONTO
		{
			get
			{
				return this._MONTO;
			}
			set
			{
				if ((this._MONTO != value))
				{
					this._MONTO = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_SUBTIPOS_CONTROL_BANCARIO_FILTROResult
	{
		
		private System.Nullable<int> _SUBTIPO;
		
		private string _DESCRIPCION;
		
		public PROC_OBT_SUBTIPOS_CONTROL_BANCARIO_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTIPO", DbType="Int")]
		public System.Nullable<int> SUBTIPO
		{
			get
			{
				return this._SUBTIPO;
			}
			set
			{
				if ((this._SUBTIPO != value))
				{
					this._SUBTIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_SUBTIPOS_X_TIPO_CONTROL_BANCARIO_FILTROResult
	{
		
		private System.Nullable<int> _SUBTIPO;
		
		private string _DESCRIPCION;
		
		public PROC_OBT_SUBTIPOS_X_TIPO_CONTROL_BANCARIO_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTIPO", DbType="Int")]
		public System.Nullable<int> SUBTIPO
		{
			get
			{
				return this._SUBTIPO;
			}
			set
			{
				if ((this._SUBTIPO != value))
				{
					this._SUBTIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_SUBTIPOS_TODOS_FILTROResult
	{
		
		private System.Nullable<int> _SUBTIPO;
		
		private string _DESCRIPCION;
		
		public PROC_OBT_SUBTIPOS_TODOS_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTIPO", DbType="Int")]
		public System.Nullable<int> SUBTIPO
		{
			get
			{
				return this._SUBTIPO;
			}
			set
			{
				if ((this._SUBTIPO != value))
				{
					this._SUBTIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_CONCILIACIONES_FILTROResult
	{
		
		private string _CONCILIACION;
		
		public PROC_OBT_CONCILIACIONES_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONCILIACION", DbType="VarChar(200)")]
		public string CONCILIACION
		{
			get
			{
				return this._CONCILIACION;
			}
			set
			{
				if ((this._CONCILIACION != value))
				{
					this._CONCILIACION = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_CONCILIACIONES_TODAS_FILTROResult
	{
		
		private string _CONCILIACION;
		
		private string _COMPLETO;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		public PROC_OBT_CONCILIACIONES_TODAS_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONCILIACION", DbType="VarChar(50)")]
		public string CONCILIACION
		{
			get
			{
				return this._CONCILIACION;
			}
			set
			{
				if ((this._CONCILIACION != value))
				{
					this._CONCILIACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLETO", DbType="VarChar(200)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this._CREATEDATE = value;
				}
			}
		}
	}
	
	public partial class PROC_OBT_CUENTAS_BANCARIAS_FILTROResult
	{
		
		private string _CUENTA_BANCO;
		
		private string _COMPLETO;
		
		public PROC_OBT_CUENTAS_BANCARIAS_FILTROResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUENTA_BANCO", DbType="VarChar(22)")]
		public string CUENTA_BANCO
		{
			get
			{
				return this._CUENTA_BANCO;
			}
			set
			{
				if ((this._CUENTA_BANCO != value))
				{
					this._CUENTA_BANCO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLETO", DbType="VarChar(100)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
